---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    test-iperf3: server
  name: iperf3-server
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      test-iperf3: server
  template:
    metadata:
      labels:
        test-iperf3: server
    spec:
      containers:
      - name: iperf3-server
        image: networkstatic/iperf3
        args:
          - -s
        ports:
        - containerPort: 5201
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test-iperf3: client
  name: iperf3-client
spec:
  containers:
  - name: iperf3-client
    image: networkstatic/iperf3
    args:
      - -c
      - iperf3-server
  restartPolicy: OnFailure
  nodeSelector:
    kubernetes.io/hostname: k8s-minion-1
